# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'images.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Photo = QtWidgets.QLabel(self.centralwidget)
        self.Photo.setGeometry(QtCore.QRect(0, 10, 581, 501))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/5X9Zpmw.jpg"))
        self.Photo.setScaledContents(True)
        self.Photo.setObjectName("Photo")
        self.Previous = QtWidgets.QPushButton(self.centralwidget)
        self.Previous.setGeometry(QtCore.QRect(60, 522, 181, 31))
        self.Previous.setObjectName("Previous")
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setGeometry(QtCore.QRect(330, 522, 171, 31))
        self.Next.setObjectName("Next")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #Inserted Content
        self.photoPaths=["C:/Users/DELL/Pictures/5X9Zpmw.jpg","C:/Users/DELL/Pictures/0Xun9D3.jpg"]
        self.photoIndex=0
        #Inserted Content
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Next.clicked.connect(lambda:self.changePhoto(1))
        self.Previous.clicked.connect(lambda:self.changePhoto(-1))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Previous.setText(_translate("MainWindow", "Previous"))
        self.Next.setText(_translate("MainWindow", "Next"))

    #Inserted Content
    def changePhoto(self,dirx):
        self.photoIndex+=dirx
        if self.photoIndex >= len(self.photoPaths):
            self.photoIndex=0
        elif self.photoIndex <0:
            self.photoIndex= len(self.photoPaths)-1
        self.Photo.setPixmap(QtGui.QPixmap(self.photoPaths[self.photoIndex])) 
    #Inserted Content 







if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
